#!/root/.notebooklm-venv/bin/python3
"""
vault-plugin-discover — discover third-party `vault-*` binaries that aren't
in the core CATEGORIES map. Pairs with `vault-plugin-safety-scan` (Hook /
MCP / shell-eval risk).

The vault umbrella's `CATEGORIES` dict lists curated tools. Anything that
matches `vault-*` on PATH but isn't in that dict counts as a "plugin" — could
be a forked tool, an experimental script, or a third-party add-on.

This CLI:
  1. Scans /usr/local/bin/ for `vault-*` binaries
  2. Cross-references with CATEGORIES (loaded from the vault.py umbrella)
  3. Lists uncategorized plugins + their first-line description (if shebang-Python)
  4. Optionally writes a markdown summary to 06-Audits/

Usage:
  vault-plugin-discover                # interactive list
  vault-plugin-discover --json         # machine-readable
  vault-plugin-discover --markdown <path>   # write audit MD
"""
from __future__ import annotations
import argparse, importlib.util, json, sys
from datetime import datetime, timezone
from pathlib import Path

BIN_DIR = Path("/usr/local/bin")
PREFIX = "vault-"
UMBRELLA = Path("/root/obsidian-vault/.vault-tools/scripts/vault.py")


def load_known_tools() -> set:
    """Extract every full-binary-name from the umbrella CATEGORIES dict."""
    spec = importlib.util.spec_from_file_location("_vault_umbrella", UMBRELLA)
    if spec is None or spec.loader is None:
        return set()
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception:
        return set()
    cats = getattr(mod, "CATEGORIES", {})
    out = set()
    for items in cats.values():
        for _, full, _ in items:
            out.add(full)
    return out


def shebang_summary(path: Path) -> str:
    """Pull the first non-shebang docstring line."""
    try:
        with open(path) as f:
            head = [next(f, "") for _ in range(20)]
    except Exception:
        return ""
    in_doc = False
    for ln in head:
        ln = ln.rstrip()
        if not in_doc and ln.startswith('"""'):
            in_doc = True
            ln = ln.lstrip('"').strip()
            if ln:
                return ln[:120]
            continue
        if in_doc and ln:
            return ln[:120]
    # No docstring — return shebang or first comment
    for ln in head:
        if ln.startswith("#") and not ln.startswith("#!"):
            return ln.lstrip("# ").rstrip()[:120]
    return ""


def discover() -> list[dict]:
    known = load_known_tools()
    out = []
    for f in sorted(BIN_DIR.iterdir()):
        if not f.name.startswith(PREFIX):
            continue
        if not f.is_file():
            continue
        if f.name == "vault" or f.name in known:
            continue
        out.append({
            "name": f.name,
            "path": str(f),
            "size_kb": round(f.stat().st_size / 1024, 1),
            "summary": shebang_summary(f),
        })
    return out


def main() -> int:
    ap = argparse.ArgumentParser(prog="vault-plugin-discover")
    ap.add_argument("--json", action="store_true", help="machine-readable JSON")
    ap.add_argument("--markdown", type=Path,
                    help="write audit markdown to this path")
    args = ap.parse_args()

    plugins = discover()
    if args.json:
        print(json.dumps(plugins, indent=2, ensure_ascii=False))
        return 0

    if args.markdown:
        lines = [
            f"---",
            f"name: plugin discovery {datetime.now(timezone.utc):%Y-%m-%d}",
            f"type: audit",
            f"created: {datetime.now(timezone.utc):%Y-%m-%d}",
            f"updated: {datetime.now(timezone.utc):%Y-%m-%d}",
            f'tags: ["#type/audit", "plugin", "safety"]',
            f"---",
            f"",
            f"# Plugin discovery — {len(plugins)} uncategorized `vault-*` binary",
            f"",
            f"Generated by `vault-plugin-discover`. Compares `/usr/local/bin/vault-*` against the umbrella `CATEGORIES` dict. Anything on PATH but not in the dict counts as a third-party / experimental / forked tool.",
            f"",
        ]
        if not plugins:
            lines.append("✓ all `vault-*` binaries are categorized in the umbrella.")
        else:
            lines.append("| name | size | summary |")
            lines.append("|---|---:|---|")
            for p in plugins:
                lines.append(f"| `{p['name']}` | {p['size_kb']} KB | {p['summary'] or '(no summary)'} |")
            lines.append("")
            lines.append("**Next step**: run `vault-plugin-safety-scan` on each to surface hook-instruction / shell-exec / non-HTTPS risk.")
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"✓ wrote {args.markdown}", file=sys.stderr)
        return 0

    print(f"vault-plugin-discover — {len(plugins)} uncategorized `vault-*` binary")
    if not plugins:
        print("  ✓ all `vault-*` binaries are categorized in the umbrella.")
        return 0
    for p in plugins:
        print(f"  {p['name']:<40} ({p['size_kb']} KB)  {p['summary']}")
    print()
    print("Next: run `vault-plugin-safety-scan` to assess each one.")
    return 0 if not plugins else 1


if __name__ == "__main__":
    sys.exit(main())
